# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'RSAMainUI.ui'
#
# Created by: PyQt5 UI code generator 5.11.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(580, 523)
        MainWindow.setAcceptDrops(False)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(19, 10, 321, 61))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit_p = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_p.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_p.setObjectName("lineEdit_p")
        self.horizontalLayout.addWidget(self.lineEdit_p)
        self.label_2 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.lineEdit_q = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        self.lineEdit_q.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_q.setObjectName("lineEdit_q")
        self.horizontalLayout.addWidget(self.lineEdit_q)
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(19, 89, 481, 374))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(195, -1, -1, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_n = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_n.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_n.setObjectName("lineEdit_n")
        self.horizontalLayout_2.addWidget(self.lineEdit_n)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(30, -1, -1, -1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_3.addWidget(self.label_4)
        self.lineEdit_fn = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_fn.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_fn.setObjectName("lineEdit_fn")
        self.horizontalLayout_3.addWidget(self.lineEdit_fn)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(255, -1, -1, -1)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_4.addWidget(self.label_5)
        self.lineEdit_e = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_e.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_e.setObjectName("lineEdit_e")
        self.horizontalLayout_4.addWidget(self.lineEdit_e)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_5.addWidget(self.label_6)
        self.lineEdit_d = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_d.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_d.setObjectName("lineEdit_d")
        self.horizontalLayout_5.addWidget(self.lineEdit_d)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(255, -1, -1, -1)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_6.addWidget(self.label_7)
        self.lineEdit_M = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_M.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_M.setObjectName("lineEdit_M")
        self.horizontalLayout_6.addWidget(self.lineEdit_M)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_8.addWidget(self.label_9)
        self.lineEdit_C = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_C.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_C.setObjectName("lineEdit_C")
        self.horizontalLayout_8.addWidget(self.lineEdit_C)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_9.addWidget(self.label_10)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Consolas")
        font.setPointSize(20)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_9.addWidget(self.label_11)
        self.lineEdit_M2 = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.lineEdit_M2.setFocusPolicy(QtCore.Qt.NoFocus)
        self.lineEdit_M2.setObjectName("lineEdit_M2")
        self.horizontalLayout_9.addWidget(self.lineEdit_M2)
        self.verticalLayout.addLayout(self.horizontalLayout_9)
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(370, 30, 101, 31))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 580, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actiona_DA = QtWidgets.QAction(MainWindow)
        self.actiona_DA.setObjectName("actiona_DA")
        self.actiona_about = QtWidgets.QAction(MainWindow)
        self.actiona_about.setObjectName("actiona_about")
        self.menu.addAction(self.actiona_DA)
        self.menu.addAction(self.actiona_about)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "RSA加解密演示"))
        self.label.setText(_translate("MainWindow", "p="))
        self.label_2.setText(_translate("MainWindow", "q="))
        self.label_3.setText(_translate("MainWindow", "n=p×q="))
        self.label_4.setText(_translate("MainWindow", "φ(n)=(p-1)×(q-1)="))
        self.label_5.setText(_translate("MainWindow", "e="))
        self.label_6.setText(_translate("MainWindow", "d=e^(-1) (modφ(n))="))
        self.label_7.setText(_translate("MainWindow", "M="))
        self.label_8.setText(_translate("MainWindow", "Encrypt:"))
        self.label_9.setText(_translate("MainWindow", "C=M^e (modn)="))
        self.label_10.setText(_translate("MainWindow", "Decrypt:"))
        self.label_11.setText(_translate("MainWindow", "M=C^d (modn)="))
        self.pushButton.setText(_translate("MainWindow", "New Instance"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.actiona_DA.setText(_translate("MainWindow", "辗转相除法演示"))
        self.actiona_about.setText(_translate("MainWindow", "关于"))

